name: Deploy FTP Infra
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="s3_bucket_name=${S3_BUCKET_NAME}" \
            -var="s3fs_credentials=${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}"