version: '3'
services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      - LDAP_ORGANISATION=MiEmpresa
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=password123
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./certs:/container/service/slapd/assets/certs
    restart: always