- name: Instalar Bind9 y utilidades
  apt:
    name:
      - bind9
      - bind9-utils
      - dnsutils
    state: present
    update_cache: yes
  tags: dns

- name: Crear archivo ddns.key
  copy:
    dest: /etc/bind/ddns.key
    content: |
      key DHCP_UPDATER {
        algorithm HMAC-MD5;
        secret "{{ tsig_secret }}";
      };
    owner: bind
    group: bind
    mode: '0640'
  tags: dns

- name: Permitir bind9 en ufw si está instalado
  command: ufw allow bind9
  when: ansible_facts.packages['ufw'] is defined
  ignore_errors: yes
  tags: dns

- name: Crear archivos de zonas directas
  template:
    src: db.directa.j2
    dest: "/var/lib/bind/db.{{ item }}"
    owner: bind
    group: bind
    mode: '0644'
  loop:
    - damian.local
  tags: dns

- name: Crear archivos de zonas inversas
  template:
    src: db.inversa.j2
    dest: "/var/lib/bind/db.{{ item }}"
    owner: bind
    group: bind
    mode: '0644'
  loop:
    - 53.168.192.in-addr.arpa
    - 54.168.192.in-addr.arpa
    - 60.168.192.in-addr.arpa
    - 70.168.192.in-addr.arpa
    - 5.1.0.0.3.1.0.0.4.1.0.2.ip6.arpa
  tags: dns

- name: Plantilla de named.conf.options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Reiniciar bind9
  tags: dns

- name: Plantilla de named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Reiniciar bind9
  tags: dns

- name: Verificar sintaxis de bind9
  command: named-checkconf
  tags: dns

- name: Verificar zonas DNS
  command: named-checkzone {{ item.nombre }} /var/lib/bind/{{ item.fichero }}
  loop:
    - { nombre: damian.local, fichero: db.damian.local }
    - { nombre: 60.168.192.in-addr.arpa, fichero: db.60.168.192 }
    - { nombre: 70.168.192.in-addr.arpa, fichero: db.70.168.192 }
    - { nombre: 53.168.192.in-addr.arpa, fichero: db.53.168.192 }
    - { nombre: 54.168.192.in-addr.arpa, fichero: db.54.168.192 }
    - { nombre: 5.1.0.0.3.1.0.0.4.1.0.2.ip6.arpa, fichero: db.5.1.0.0.3.1.0.0.4.1.0.2.ip6.arpa }
  tags: dns
 
- name: Reiniciar Bind9
  service:
    name: bind9
    state: restarted
    enabled: yes
  tags: dns

- name: Configurar archivos /etc/systemd/resolved.conf
  import_tasks: resolved.yml
  tags: dns
