- name: Configurar /etc/systemd/resolved
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: '0664'
  notify: Reiniciar systemd-resolved
  tags: dns

- name: Asegurarse de que systemd-resolved está activo
  service:
    name: systemd-resolved
    state: started
    enabled: yes
  tags: dns
