- name: Instalar chrony
  apt:
    name: chrony
    state: present

- name: Configurar archivo /etc/chrony/chrony.conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reiniciar Chrony

- name: Asegurar que el servicio chrony esté activo
  systemd:
    name: chrony
    enabled: yes
    state: started
